version: '3'
services:
    gradle:
        build:
            context: .
            dockerfile: Dockerfile_junit
        ports:
            - 8888:80
        depends_on:
            - db
#        volumes:
#            - "./volumes/app:/var/www/html"
        links:
            - db
    db:
         build:
           context: .
           dockerfile: Dockerfile_mysql
         environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
            - MYSQL_DATABASE=massive_mailer_unittest
#        ports:
#            - "13306:3306"
#        volumes:
#            - "./data/mysql:/var/lib/mysql"
