version: '3'
services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
