version: '2'
services:
    mysql:
        container_name: gradle-cucumber-mysql
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - "./mysql/scripts:/docker-entrypoint-initdb.d"
    gradle-cucumber:
        container_name: gradle-cucumber
        build:
            context: .
            dockerfile: DockerfileCucumber
        ports:
            - "80:80"
        depends_on:
            - mysql
