CREATE DATABASE IF NOT EXISTS massive_mailer_test DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS massive_mailer_unittest DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS massive_mailer_development DEFAULT CHARACTER SET utf8mb4;

